## 配置子项目的端口号
server:
  port: 8001

## 关于Eureka的配置
# 要把服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: SpringCloud_provider_dept_8001_hystrix # 修改eureka上的默认描述信息
    prefer-ip-address: true # 鼠标悬停在Eureka监控页面上Status里的连接上 左下角可以显示真实IP地址
# eureka跳转信息配置
info:
  app.name: wq-springcloud
  company.name: FZU

## mybatis的配置
mybatis:
  type-aliases-package: com.wq.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  ## 数据库字段转换成驼峰的形式
#  configuration:
#    map-underscore-to-camel-case: true
## spring的数据库配置
spring:
  application:
    # 这里服务提供者的应用可以使用中划线 但不能使用下划线!
    name: SpringCloud-provider-dept
  datasource:
    ## 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root