## "配置服务中心"应用的 端口
server:
  port: 3344
## "配置服务中心"应用的 应用服务名
spring:
  application:
    name: springcloud-config-server
  # 连接远程的配置仓库(可以连接git 也可以连接svn)
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LinuxRussia/springcloud-config.git # https链接
